---
abstract: 'routing helper for RESTful operations'
author:
  - 'Jens Berthold <cpan-mp-restroutes@jebecs.de>'
build_requires:
  Module::Build: 0.3601
  Test::Mojo: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-RESTRoutes
requires:
  Lingua::EN::Inflect: 1.895
  Modern::Perl: 1.20121103
  Mojo::Base: 0
  perl: v5.8.8
version: 0.010009
