---
abstract: 'routing helper for RESTful operations'
author:
  - 'Jens Berthold <cpan-mp-restroutes@jebecs.de>'
build_requires:
  Module::Build: '0.28'
  Test::Mojo: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.143240'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-RESTRoutes
requires:
  Lingua::EN::Inflect: '0'
  Modern::Perl: '0'
  Mojo::Base: '0'
  perl: v5.8.8
version: '0.010012'
